; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno
src_dir = .

[env]
build_flags  =
   -Wall -Wextra
test_framework = googletest
build_src_filter = 
  +<*>
  -<.git/>
  -<.svn/>
  -<test/**>
  -<examples/**>
  +<examples/NmraDccAccessoryDecoder_Pulsed_8/**>
lib_ldf_mode = deep

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    ; NmraDcc
    EEPROM
monitor_speed = 115200
monitor_echo = yes
build_flags =
    -mcall-prologues
    -std=gnu++11

[env:xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board = seeed_xiao_rp2040
lib_deps =
;   NmraDcc
;   U8g2
   EEPROM   
   adafruit/Adafruit TinyUSB Library
build_flags = 
   -std=gnu++11
   -DUSE_TINYUSB
   -I"${PROJECT_CORE_DIR}\packages\framework-arduino-samd-seeed\libraries\Adafruit_TinyUSB_Arduino\src\arduino"

[env:native]
platform = native
lib_compat_mode = off
lib_deps =
      ArduinoFake
